### ISSUE TITLE
Not working at all with VSC 0.9

### ISSUE THREAD

**Issue by ig0rsky** [kode80/VSCUnity#5]
Is this project dead ?

**Comment by BearHeathen** [comment]
Not dead, more like redundant. Another plugin was developed and made available on the asset store. See the below links for more information. I'd be interested in continuing to help out if anything needs to be done, kode.
- https://code.visualstudio.com/docs/runtimes/unity
- https://www.assetstore.unity3d.com/en/#!/content/45320

**Comment by ig0rsky** [comment]
I'm already using this, I just wanted to have the syntax highlighting to be honest. Because that plugin doesn't provide you with syntax highlighting.

**Comment by BearHeathen** [comment]
I'm not sure that's something we can implement either way. According to [this page](https://code.visualstudio.com/Docs/languages/overview), the base editor doesn't support C# syntax highlighting, only IntelliSense, refactoring, etc. I think this might be due to the cross-platform focus of the editor with regards to C# in particular, but I'm not certain.  I'll look into it though and get back with you. It is rather odd that this isn't supported by default, seeing the wide usage C# enjoys. See [here](https://code.visualstudio.com/docs/languages/csharp) for more information about the base C# functionality in VS Code.

In the meantime, there is the [Code Colorizer](https://code.visualstudio.com/docs/customization/colorizer), which allows you to specify your own syntax highlighting rules if you feel so inclined.

**Comment by ig0rsky** [comment]
Yeah, I tried to use the code colorizer, Here is what i did step by step,
run the colorizer
0- Run yo code in your directory
1- Selected new language support
2- Googled for a .tmlanguage file. found this one : https://raw.githubusercontent.com/lostfictions/Unity3DSublimeSyntax/master/UnityC%23.tmLanguage
3- Entered a unique name : Unity
4- Entered the id which I assumed to be: csharp
5- Entered the editor extension name : UnityC#
6- Entered the file extension : .cs
7- Moved the Unity folder that's created in my directory to .vscode/extensions/ 

There is no added syntax colouring, except for the default one that you get out of the box with C#. I mean it didn't work. If you can get it to work or find a solution , please let me know. :+1:

**Comment by kode80** [comment]
Hi folks. I took a look at the current version of VSC last week and they've changed folder structure and plugin format enough to break VSCUnity. For me personally what sucks the most is that pre-break I had shader highlighting, completion and inline documentation working nicely.

I'm currently wrapping up another project so don't have the time to look into this right now. I based my shader plugin on the omnisharp VSC plugin, so if anyone wants to have a bash at fixing it feel free to compare the two and see what's changed.

Looking at the VSC site, it appears they're getting close to officially supporting full language plugins so if no one's put out a solution at that point, I'll take another crack at it.

**Comment by BearHeathen** [comment]
Yea, I saw that shader goodness you had going on. A shame they went an broke it. However, OmniSharp itself seems to be having issues. I'm not finding a VSC-specific repo on the OmniSharp Github. It is totally possible, however, that [I'm not looking in the correct place](https://github.com/omnisharp?utf8=%E2%9C%93&query=) (in which case I don't know where it would be). 

But since VSC 0.8, [OmniSharp has been having some issues](https://code.visualstudio.com/Issues/List), it would seem. .
